merging corrections to master branch
apo-oi-web/APO_Website pull request #24
Opened 2021-04-15 18:36 UTC by eesmith42

2021-04-15 20:47 UTC, henryposkanzer requested changes

2021-04-15 20:47 UTC, henryposkanzer commented on public_html/contact.html
> +				<p style="text-align: center;">The President is in charge of supervising the chapter and all other officers. They are at every brother and executive board meeting, represent the chapter at all fu
I think this page looks weird. All the headings and email addresses are left-justified, and the descriptions are centered. They should both be left-justified or both be centered.

2021-04-22 21:36 UTC, eesmith42 reviewed
looks good to me. edited center tags to whole sections, not just description. review again just in case?

2021-04-23 17:19 UTC, henryposkanzer approved these changes

2021-04-30 15:49 UTC, merged